const styles = {
  main: { display: 'flex', flexDirection: 'column' },
  artistStatus: {
    display: 'flex',
    columnGap: '16px',
    padding: '20px 0',
    border: '1px solid #D5D5D5',
    borderRadius: '4px',
    marginBottom: '20px',
    width: '632px',
    justifyContent: 'center',
    alignItems: 'center',
  },
  artistStatusText: {
    fontWeight: '700',
    fontSize: '32px',
    lineHeight: '38.73px',
  },
  myOrders: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '40px',
    margin: '20px 0 80px 0',
  },
  myOrdersTitle: { fontWeight: '500', fontSize: '36px', lineHeight: '43.57px' },
  orders: {
    display: 'grid',
    gridTemplateColumns: '625px 625px',
    columnGap: '12px',
  },
  order: {
    display: 'flex',
    columnGap: '12px',
    borderRadius: '4px',
    border: '1px solid #D5D5D5',
    padding: '20px',
  },
  artImg: {
    objectFit: 'cover',
    objectPosition: 'center',
    borderRadius: '4px',
    width: '175px',
    height: '186px',
  },
  orderInfo: { display: 'flex', flexDirection: 'column', rowGap: '12px' },
  deliveryInfo: { display: 'flex', flexDirection: 'column', rowGap: '4px' },
  deliveryStatus: {
    fontWeight: '700',
    fontSize: '32px',
    lineHeight: '38.73px',
  },
  deliveryDate: {
    fontWeight: '600',
    fontSize: '24px',
    lineHeight: '33.6px',
  },
  deliveryType: {
    fontWeight: '400',
    fontSize: '24px',
    lineHeight: '33.6px',
  },
  artInfo: { display: 'flex', flexDirection: 'column', rowGap: '4px' },
  artAuthor: {
    fontWeight: '500',
    fontSize: '28px',
    lineHeight: '39.2px',
  },
  artName: {
    fontWeight: '600',
    fontSize: '24px',
    lineHeight: '33.6px',
    color: '#757575',
  },
  myData: { display: 'flex', flexDirection: 'column', rowGap: '40px' },
  myDataTitle: { fontWeight: '500', fontSize: '36px', lineHeight: '43.57px' },
  subscription: {
    display: 'flex',
    flexDirection: 'column',
    padding: '20px 24px',
    border: '1px solid #D5D5D5',
    borderRadius: '4px',
    width: '858px',
    rowGap: '10px',
  },
  subscriptionInfo: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '20px',
  },
  subscriptionTitle: {
    fontWeight: '700',
    fontSize: '32px',
    lineHeight: '38.73px',
  },
  subscriptionOptions: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '14px',
  },
  subscriptionOption: {
    fontWeight: '400',
    fontSize: '24px',
    lineHeight: '33.6px',
    display: 'flex',
    columnGap: '12px',
  },
  subscriptionExpiration: {
    fontWeight: '600',
    fontSize: '24px',
    lineHeight: '33.6px',
  },
  subscriptionButtons: { display: 'flex', columnGap: '40px' },
};

export default styles;
