# Generated by Django 5.0.6 on 2024-06-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_ordermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='in_delivery',
            field=models.BooleanField(default=False, verbose_name='Передано в доставку'),
        ),
    ]
