# Generated by Django 5.0.6 on 2024-06-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_shoppingcartmodel_is_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(choices=[('online', 'онлайн'), ('on_receiving', 'при получении')], max_length=100, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='delivery_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ожидаемая дата доставки'),
        ),
    ]
