# Generated by Django 5.0.6 on 2024-06-25 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artworkmodel_is_on_sold'),
        ('market', '0003_alter_ordermodel_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchasemodel',
            constraint=models.UniqueConstraint(fields=('artwork',), name='unique_artwork'),
        ),
    ]
