const styles = {
  mainContainer: { display: 'flex', flexDirection: 'column', margin: '80px' },
  container: { display: 'flex', columnGap: '100px' },
  artContainer: { display: 'flex', flexDirection: 'column', rowGap: '40px' },
  artHeaderContainer: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '12px',
  },
  artInfoContainers: { display: 'flex', columnGap: '166px' },
  artInfoContainer: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '24px',
  },
  artButtonsContainer: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '28px',
  },
  artistInfoContainer: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '20px',
  },
  artistDescriptionContainer: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '16px',
  },
  artistTextDefault: {
    fontSize: '24px',
    fontWeight: '400',
    lineHeight: '33.6px',
  },
  artistTextBold: {
    fontSize: '24px',
    fontWeight: '600',
    lineHeight: '33.6px',
  },
  artistExhibitions: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '12px',
  },
  artistExhibitionsContainer: { display: 'flex', flexDirection: 'column' },
  artistName: {
    fontSize: '36px',
    fontWeight: '500',
    lineHeight: '43.57px',
    color: '#252525',
  },
  artName: {
    fontSize: '32px',
    fontWeight: '500',
    lineHeight: '38.73px',
    color: '#757575',
  },
  artImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    objectPosition: 'center',
    borderRadius: '4px',
  },
  artInfoTitle: {
    fontSize: '24px',
    fontWeight: '400',
    lineHeight: '33.6px',
    color: '#252525',
  },
  artInfoValue: {
    fontSize: '24px',
    fontWeight: '400',
    lineHeight: '33.6px',
    color: '#757575',
    marginLeft: '5px',
  },
  title: {
    fontSize: '36px',
    fontWeight: '500',
    lineHeight: '43.57px',
    margin: '80px 0 40px 0',
  },
  progressionButton: {
    bgcolor: 'white',
    padding: '28px 0',
    fontSize: '32px',
    lineHeight: '38.73px',
    width: '100%',
    color: '#252525',
    borderColor: '#757575',
    textTransform: 'none',
    display: 'flex',
    alignItems: 'flex-start',
    ':hover': {
      backgroundColor: 'white',
    },
  },
  imgContainer: { position: 'relative' },
  artistImg: {
    width: '410px',
    height: '415px',
    objectFit: 'contain',
    objectPosition: 'center',
    borderRadius: '4px',
  },
  imgButtonTop: {
    position: 'absolute',
    top: '0',
    right: '0',
    bgcolor: 'white',
    padding: '0',
    width: '65px',
    height: '65px',
    color: '#252525',
    display: 'flex',
    alignItems: 'center',
    ':hover': {
      backgroundColor: 'white',
    },
  },
  imgButtonBottom: {
    position: 'absolute',
    bottom: '0',
    right: '0',
    bgcolor: 'white',
    padding: '0',
    width: '65px',
    height: '65px',
    color: '#252525',
    display: 'flex',
    alignItems: 'center',
    ':hover': {
      backgroundColor: 'white',
    },
  },
};

export default styles;
