# Generated by Django 5.0.6 on 2024-06-23 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='StyleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='ArtworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название работы')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год создания')),
                ('size', models.CharField(max_length=100, verbose_name='Размер работы')),
                ('brushstrokes_material', models.CharField(max_length=200, verbose_name='Техника, материал')),
                ('is_estimate', models.BooleanField(default=False, verbose_name='Оценка получена')),
                ('is_on_sold', models.CharField(choices=[('not posted', 'не размещено'), ('on sale', 'на продаже'), ('sold', 'продано')], default='не размещено', verbose_name='Статус продажи')),
                ('orientation', models.CharField(blank=True, choices=[('horizontal', 'горизонтальная'), ('vertical', 'вертикальная')], max_length=100, null=True, verbose_name='Ориентация работы')),
                ('decoration', models.CharField(max_length=200, verbose_name='Оформление')),
                ('author_signature', models.CharField(max_length=200, verbose_name='Наличие авторской подписи')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото работы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание картины')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistmodel', verbose_name='Автор работы')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.seriesmodel', verbose_name='Серия работ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.categorymodel', verbose_name='Категория')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.stylemodel', verbose_name='Стиль работы')),
            ],
            options={
                'verbose_name': 'Произведение искусства',
                'verbose_name_plural': 'Произведения искусства',
            },
        ),
        migrations.CreateModel(
            name='ArtworkPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.IntegerField(verbose_name='Цена оригинала')),
                ('copy_price', models.IntegerField(blank=True, null=True, verbose_name='Цена постера')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации цены')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artworkmodel', verbose_name='Произведение искусства')),
            ],
            options={
                'verbose_name': 'Цена произведения искусства',
                'verbose_name_plural': 'Цены произведений искусства',
            },
        ),
        migrations.CreateModel(
            name='FavoriteArtworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artworkmodel', verbose_name='Произведение искусства')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ценитель искусства')),
            ],
            options={
                'verbose_name': 'Избранное произведение',
                'verbose_name_plural': 'Избранные произведения',
            },
        ),
        migrations.AddConstraint(
            model_name='favoriteartworkmodel',
            constraint=models.UniqueConstraint(fields=('artwork', 'user'), name='favorite_artwork'),
        ),
    ]
