# Generated by Django 5.0.6 on 2024-06-17 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя и фамилия')),
                ('about_artist', models.CharField(max_length=200, verbose_name='Об авторе')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название образовательного учреждения')),
            ],
            options={
                'verbose_name': 'Образовательное учреждение',
                'verbose_name_plural': 'Образовательные учреждения',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название выставки')),
                ('period', models.CharField(max_length=50, verbose_name='Период проведения выставки')),
                ('address', models.CharField(max_length=200, verbose_name='Место проведения выставки')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
            },
        ),
        migrations.CreateModel(
            name='ArtworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название работы')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год создания')),
                ('size', models.CharField(max_length=100, verbose_name='Размер работы')),
                ('brushstrokes_material', models.CharField(max_length=200, verbose_name='Техника, материал')),
                ('is_estimate', models.BooleanField(default=False, verbose_name='Оценка получена')),
                ('is_on_sold', models.CharField(choices=[('not posted', 'не размещено'), ('on sale', 'на продаже'), ('sold', 'продано')], default='не размещено', verbose_name='Статус продажи')),
                ('orientation', models.CharField(blank=True, choices=[('horizontal', 'горизонтальная'), ('vertical', 'вертикальная')], max_length=100, null=True, verbose_name='Ориентация работы')),
                ('style', models.CharField(blank=True, max_length=100, null=True, verbose_name='Стиль работы')),
                ('decoration', models.CharField(max_length=200, verbose_name='Оформление')),
                ('author_signature', models.CharField(max_length=200, verbose_name='Наличие авторской подписи')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото работы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artistmodel', verbose_name='Автор работы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Произведение искусства',
                'verbose_name_plural': 'Произведения искусства',
            },
        ),
        migrations.CreateModel(
            name='ArtworkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.CharField(max_length=200, verbose_name='Цена оригинала')),
                ('copy_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цена постера')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации цены')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artworkmodel', verbose_name='Произведение искусства')),
            ],
            options={
                'verbose_name': 'Цена произведения искусства',
                'verbose_name_plural': 'Цены произведений искусства',
            },
        ),
        migrations.CreateModel(
            name='EducationAuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_start', models.IntegerField(blank=True, null=True, verbose_name='Год начала обучения')),
                ('education_finish', models.IntegerField(blank=True, null=True, verbose_name='Год окончания обучения')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artistmodel', verbose_name='Имя и фамилия автора')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.educationmodel', verbose_name='Название учебного заведения')),
            ],
        ),
        migrations.AddField(
            model_name='artistmodel',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.educationmodel', verbose_name='Образование автора'),
        ),
        migrations.CreateModel(
            name='ExhibitionParticipantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.exhibitionmodel', verbose_name='Выставка')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artistmodel', verbose_name='Участник выставки')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название серии')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artistmodel', verbose_name='Автор серии')),
            ],
            options={
                'verbose_name': 'Серия работ',
                'verbose_name_plural': 'Серии работ',
            },
        ),
        migrations.AddField(
            model_name='artworkmodel',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.seriesmodel', verbose_name='Серия работ'),
        ),
    ]
