# Generated by Django 5.0.6 on 2024-06-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkpricemodel',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Цена произведения искусства', 'verbose_name_plural': 'Цены произведений искусства'},
        ),
    ]
