# Generated by Django 5.0.6 on 2024-06-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='educationauthormodel',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='exhibitionparticipantmodel',
            name='participant',
        ),
        migrations.AlterField(
            model_name='artworkmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistmodel', verbose_name='Автор работы'),
        ),
        migrations.RemoveField(
            model_name='educationauthormodel',
            name='education',
        ),
        migrations.RemoveField(
            model_name='exhibitionparticipantmodel',
            name='exhibition',
        ),
        migrations.AlterField(
            model_name='artworkmodel',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.seriesmodel', verbose_name='Серия работ'),
        ),
        migrations.DeleteModel(
            name='ArtistModel',
        ),
        migrations.DeleteModel(
            name='EducationAuthorModel',
        ),
        migrations.DeleteModel(
            name='EducationModel',
        ),
        migrations.DeleteModel(
            name='ExhibitionModel',
        ),
        migrations.DeleteModel(
            name='ExhibitionParticipantModel',
        ),
        migrations.DeleteModel(
            name='SeriesModel',
        ),
    ]
