# Generated by Django 5.0.6 on 2024-06-18 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_remove_seriesmodel_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artworkmodel', verbose_name='Произведение искусства')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ценитель искусства')),
            ],
            options={
                'verbose_name': 'Избранное произведение',
                'verbose_name_plural': 'Избранные произведения',
            },
        ),
        migrations.AddConstraint(
            model_name='favoriteartwork',
            constraint=models.UniqueConstraint(fields=('artwork', 'user'), name='favorite_artwork'),
        ),
    ]
