# Generated by Django 5.0.6 on 2024-06-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_alter_artworkpricemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkmodel',
            name='is_on_sold',
            field=models.CharField(choices=[('not posted', 'не размещено'), ('on sale', 'на продаже'), ('sold', 'продано')], default='not posted', verbose_name='Статус продажи'),
        ),
    ]
