# Generated by Django 5.0.6 on 2024-06-18 11:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_favoriteartwork_favoriteartwork_favorite_artwork'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteArtwork',
            new_name='FavoriteArtworkModel',
        ),
    ]
