# Generated by Django 5.0.6 on 2024-06-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_rename_favoriteartwork_favoriteartworkmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtworkPrice',
            new_name='ArtworkPriceModel',
        ),
    ]
