# Generated by Django 5.0.6 on 2024-06-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_categorymodel_stylemodel_artworkmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkpricemodel',
            name='copy_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена постера'),
        ),
        migrations.AlterField(
            model_name='artworkpricemodel',
            name='original_price',
            field=models.IntegerField(verbose_name='Цена оригинала'),
        ),
    ]
