# Generated by Django 5.0.6 on 2024-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_alter_artworkpricemodel_copy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание картины'),
        ),
    ]
