# Generated by Django 5.0.6 on 2024-06-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя и фамилия')),
                ('about_artist', models.CharField(max_length=200, verbose_name='Об авторе')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название образовательного учреждения')),
            ],
            options={
                'verbose_name': 'Образовательное учреждение',
                'verbose_name_plural': 'Образовательные учреждения',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название выставки')),
                ('period', models.CharField(max_length=50, verbose_name='Период проведения выставки')),
                ('address', models.CharField(max_length=200, verbose_name='Место проведения выставки')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
            },
        ),
        migrations.CreateModel(
            name='EducationAuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_start', models.IntegerField(blank=True, null=True, verbose_name='Год начала обучения')),
                ('education_finish', models.IntegerField(blank=True, null=True, verbose_name='Год окончания обучения')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistmodel', verbose_name='Имя и фамилия автора')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.educationmodel', verbose_name='Название учебного заведения')),
            ],
        ),
        migrations.AddField(
            model_name='artistmodel',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.educationmodel', verbose_name='Образование автора'),
        ),
        migrations.CreateModel(
            name='ExhibitionParticipantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.exhibitionmodel', verbose_name='Выставка')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistmodel', verbose_name='Участник выставки')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название серии')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistmodel', verbose_name='Автор серии')),
            ],
            options={
                'verbose_name': 'Серия работ',
                'verbose_name_plural': 'Серии работ',
            },
        ),
    ]
