# Generated by Django 5.0.6 on 2024-06-30 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название образовательного учреждения')),
            ],
            options={
                'verbose_name': 'Образовательное учреждение',
                'verbose_name_plural': 'Образовательные учреждения',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название выставки')),
                ('period', models.CharField(max_length=50, verbose_name='Период проведения выставки')),
                ('address', models.CharField(max_length=200, verbose_name='Место проведения выставки')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
            },
        ),
        migrations.CreateModel(
            name='ArtistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя и фамилия')),
                ('about_artist', models.TextField(blank=True, null=True, verbose_name='Об авторе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото автора')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='EducationAuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_start', models.IntegerField(blank=True, null=True, verbose_name='Год начала обучения')),
                ('education_finish', models.IntegerField(blank=True, null=True, verbose_name='Год окончания обучения')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistmodel', verbose_name='Имя и фамилия автора')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.educationmodel', verbose_name='Название учебного заведения')),
            ],
            options={
                'verbose_name': 'Образование автора',
                'verbose_name_plural': 'Образование авторов',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionParticipantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.exhibitionmodel', verbose_name='Выставка')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistmodel', verbose_name='Участник выставки')),
            ],
            options={
                'verbose_name': 'Выставка автора',
                'verbose_name_plural': 'Выставки авторов',
            },
        ),
        migrations.CreateModel(
            name='FavoriteArtistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistmodel', verbose_name='Автор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ценитель творчества автора')),
            ],
            options={
                'verbose_name': 'Любимый автор',
                'verbose_name_plural': 'Любимые авторы',
            },
        ),
        migrations.CreateModel(
            name='SeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название серии')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistmodel', verbose_name='Автор серии')),
            ],
            options={
                'verbose_name': 'Серия работ',
                'verbose_name_plural': 'Серии работ',
            },
        ),
        migrations.AddConstraint(
            model_name='favoriteartistmodel',
            constraint=models.UniqueConstraint(fields=('artist', 'user'), name='favorite_artist'),
        ),
    ]
