# Generated by Django 5.0.6 on 2024-06-18 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artistmodel_user_favoriteartist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteArtist',
            new_name='FavoriteArtistModel',
        ),
        migrations.RemoveField(
            model_name='artistmodel',
            name='education',
        ),
    ]
