# Generated by Django 5.0.6 on 2024-06-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_userartistmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserArtistModel',
        ),
    ]
