# Generated by Django 5.0.6 on 2024-06-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_educationauthormodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationauthormodel',
            options={'verbose_name': 'Образование автора', 'verbose_name_plural': 'Образование авторов'},
        ),
        migrations.AlterModelOptions(
            name='exhibitionparticipantmodel',
            options={'verbose_name': 'Выставка автора', 'verbose_name_plural': 'Выставки авторов'},
        ),
    ]
