# Generated by Django 5.0.6 on 2024-06-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_educationauthormodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteartistmodel',
            options={'verbose_name': 'Любимый автор', 'verbose_name_plural': 'Любимые авторы'},
        ),
    ]
