# Generated by Django 5.0.6 on 2024-06-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_alter_favoriteartistmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistmodel',
            name='about_artist',
            field=models.TextField(verbose_name='Об авторе'),
        ),
    ]
