# Generated by Django 5.0.6 on 2024-06-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artistmodel_about_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistmodel',
            name='about_artist',
            field=models.TextField(blank=True, null=True, verbose_name='Об авторе'),
        ),
        migrations.AlterField(
            model_name='artistmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото автора'),
        ),
    ]
